import {
  CanonicalManifestSchema,
  CanonicalWordSchema,
  type CanonicalManifest,
  type CanonicalWord,
} from '../../schemas/v1';

const manifestId = 'jp-study-ja-n5-starter-v1';
const importedSource = {
  manifestId,
  sourceName: 'Qwerty Learner 中文释义 + OpenJLPT 分级',
  sourceVersion: 'e0dc7a09 + 450fd50f',
} as const;
const legacySource = {
  manifestId,
  sourceName: '钟日 jp-study canonical',
  sourceVersion: null,
} as const;

export const jaN5StarterManifest: CanonicalManifest = CanonicalManifestSchema.parse({
  schemaVersion: 1,
  id: manifestId,
  contentVersion: 1,
  language: 'ja',
  level: 'N5',
  wordCount: 20,
  wordIdsSha256: '1f84b979f46e97024acfed4e0fcb4c38f5125ec8b02c153cf797af2783f10309',
  contentSha256: 'fbf70f508a81b38500164f76dd5c80d452a0c3738fbf8fa0a1abd2f582be3fe1',
  source: {
    repository: 'ibka512/jp-study',
    commitSha: '36c8129dfc364453198790b64687ff9105a3ecae',
    path: 'wordbanks/ja-001.js',
    blobSha: '72ac88e5d7f893d46acab46b96f07ae22ea80356',
    licenseSummary: 'MIT sources with OpenJLPT-derived data shared under CC BY-SA 4.0',
  },
});

export const jaN5StarterWords: readonly CanonicalWord[] = CanonicalWordSchema.array().parse(
  [
    {
      id: 'builtin-ja-core-00005',
      headword: '元気',
      reading: 'げんき',
      partOfSpeech: '名・形动',
      meaning: '精神充沛，健康。',
      source: legacySource,
    },
    {
      id: 'builtin-ja-core-00006',
      headword: '仕事',
      reading: 'しごと',
      partOfSpeech: '名・サ变动词する自',
      meaning: '工作，职业。',
      source: legacySource,
    },
    {
      id: 'builtin-ja-core-00009',
      headword: '新聞',
      reading: 'しんぶん',
      partOfSpeech: '名词',
      meaning: '报纸。',
      source: legacySource,
    },
    {
      id: 'builtin-ja-core-00010',
      headword: '洗濯',
      reading: 'せんたく',
      partOfSpeech: '名・サ变动词する他',
      meaning: '洗衣服。',
      source: legacySource,
    },
    {
      id: 'builtin-ja-core-00011',
      headword: '天気',
      reading: 'てんき',
      partOfSpeech: '名词',
      meaning: '天气。',
      source: legacySource,
    },
    {
      id: 'builtin-ja-core-00012',
      headword: '時計',
      reading: 'とけい',
      partOfSpeech: '名词',
      meaning: '钟表。',
      source: legacySource,
    },
    {
      id: 'builtin-ja-core-00014',
      headword: '病気',
      reading: 'びょうき',
      partOfSpeech: '名词',
      meaning: '疾病，生病。',
      source: legacySource,
    },
    {
      id: 'builtin-ja-core-00020',
      headword: '料理',
      reading: 'りょうり',
      partOfSpeech: '名・サ变动词する他',
      meaning: '菜肴；烹饪。',
      source: legacySource,
    },
    {
      id: 'builtin-ja-import-0b58a2ef742702',
      headword: 'あさって',
      reading: 'あさって',
      partOfSpeech: '名词',
      meaning: '后天',
      source: importedSource,
    },
    {
      id: 'builtin-ja-import-7784849a533833',
      headword: 'あまり',
      reading: 'あまり',
      partOfSpeech: '副词·形容动词',
      meaning: '（不）太，（不）怎么样；过分',
      source: importedSource,
    },
    {
      id: 'builtin-ja-import-6efb6040d8e32e',
      headword: 'ある',
      reading: 'ある',
      partOfSpeech: '自动词1',
      meaning: '（植物、没有生命的物体）有；存在',
      source: importedSource,
    },
    {
      id: 'builtin-ja-import-2f408e95e9c307',
      headword: 'いかが',
      reading: 'いかが',
      partOfSpeech: '副词',
      meaning: '怎么样，怎么办',
      source: importedSource,
    },
    {
      id: 'builtin-ja-import-1f90abf644753f',
      headword: 'おいしい',
      reading: 'おいしい',
      partOfSpeech: 'イ形',
      meaning: '好吃的，美味的',
      source: importedSource,
    },
    {
      id: 'builtin-ja-import-8a84460c2a872d',
      headword: 'お手洗い',
      reading: 'おてあらい',
      partOfSpeech: '名词',
      meaning: '洗手间',
      source: importedSource,
    },
    {
      id: 'builtin-ja-import-749af11afdc9c9',
      headword: 'かばん',
      reading: 'かばん',
      partOfSpeech: '名词',
      meaning: '包',
      source: importedSource,
    },
    {
      id: 'builtin-ja-import-c0129359d3087c',
      headword: 'きれい',
      reading: 'きれい',
      partOfSpeech: '形容动词',
      meaning: '漂亮的，美丽的；干净的',
      source: importedSource,
    },
    {
      id: 'builtin-ja-import-c00a58d8468ac1',
      headword: 'しかし',
      reading: 'しかし',
      partOfSpeech: '接续词',
      meaning: '可是，不过',
      source: importedSource,
    },
    {
      id: 'builtin-ja-import-1a687c7f963ceb',
      headword: 'それから',
      reading: 'それから',
      partOfSpeech: '接续词',
      meaning: '然后；还有',
      source: importedSource,
    },
    {
      id: 'builtin-ja-import-c934ba24a83d6a',
      headword: 'それでは',
      reading: 'それでは',
      partOfSpeech: '接续词',
      meaning: '那么',
      source: importedSource,
    },
    {
      id: 'builtin-ja-import-4b1ae7c13235f2',
      headword: 'たくさん',
      reading: 'たくさん',
      partOfSpeech: '名词·副词',
      meaning: '很多',
      source: importedSource,
    },
  ].map((word) => ({
    schemaVersion: 1,
    language: 'ja',
    phonetic: null,
    level: 'N5',
    difficulty: 0,
    tags: ['JLPT', 'N5', '高频词'],
    isBuiltIn: true,
    dataVersion: 1,
    ...word,
  })),
);
